#数据库配置

#PostgreSQL配置
#org.postgresql.Driver
#jdbc:postgresql://localhost:5432/SpringCloud

#MariaDB配置
#mySql com.mysql.jdbc.Driver
#jdbc:mariadb://localhost:3306/data_base

db:
  info:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/data_base
    username: root
    password: 111111qwe


druid:
  type: com.alibaba.druid.pool.DruidDataSource
  master:
    driverClassName: ${db.info.driverClassName}
    url: ${db.info.url}
    username: ${db.info.username}
    password: ${db.info.password}
    initialSize: 5
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true

  slave:
    driverClassName: ${db.info.driverClassName}
    url: ${db.info.url}
    username: ${db.info.username}
    password: ${db.info.password}
    initialSize: 5
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true