#---------------------------------------------------------------------
spring:
  profiles:
    active: dev
#---------------------------------------------------------------------
server:
  port: 9000
  servlet:
    context-path: /eureka-server
#---------------------------------------------------------------------
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: ${server.servlet.context-path}/actuator/info #eureka注册中心的url link
    health-check-url-path: ${server.servlet.context-path}/actuator/health #健康检查的url
    hostname: localhost
  client:
    register-with-eureka: true #是否注册到注册中心
    fetch-registry: false #是否从注册中心拉取注册服务列表
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
#---------------------------------------------------------------------
info:
  version: 1.0.0
  app:
    name: ${spring.application.name}
#---------------------------------------------------------------------